tasks:
  - name: Dev Server
    init: |
      docker compose build
      docker compose create
    command: docker compose up

image:
  file: .gitpod.Dockerfile

ports:
  - port: 8000 # Airbyte dev server web frontend
    onOpen: open-browser
  - port: 8001 # Airbyte internal API host
    onOpen: ignore
  - port: 7233 # Airbyte temporal orchestration host
    onOpen: ignore

vscode:
  extensions:
    - github.vscode-pull-request-github
    - ms-azuretools.vscode-docker
    - ms-python.python
